virtual_modifiers:
  - KEY_YEN

modmap:
  - name: Physical JIS keyboard with ANSI layout
    remap:
      KEY_RO: KEY_RIGHTCTRL

  - name: Alternative keybindings for Ctrl and Esc
    remap:
      KEY_CAPSLOCK:
        held: KEY_LEFTCTRL
        alone: KEY_ESC
        alone_timeout_millis: 400

  - name: Use Space as a layer key
    remap:
      KEY_SPACE:
        held: KEY_YEN # KEY_YEN is set as a virtual modifier
        alone: KEY_SPACE
        alone_timeout_millis: 300

keymap:
  - name: Sway commands (default mode)
    mode: default
    remap:
      # Space-layer: from here
      # focus
      KEY_YEN-KEY_H: { launch: ["swaymsg", "focus", "left" ] }
      KEY_YEN-KEY_J: { launch: ["swaymsg", "focus", "down" ] }
      KEY_YEN-KEY_K: { launch: ["swaymsg", "focus", "up"   ] }
      KEY_YEN-KEY_L: { launch: ["swaymsg", "focus", "right"] }
      # move
      KEY_YEN-KEY_LEFT:  { launch: ["swaymsg", "move", "left" ] }
      KEY_YEN-KEY_UP:    { launch: ["swaymsg", "move", "down" ] }
      KEY_YEN-KEY_DOWN:  { launch: ["swaymsg", "move", "up"   ] }
      KEY_YEN-KEY_RIGHT: { launch: ["swaymsg", "move", "right"] }
      # workspace
      KEY_YEN-KEY_1: { launch: ["swaymsg", "workspace", "main"  ] }
      KEY_YEN-KEY_2: { launch: ["swaymsg", "workspace", "sub"   ] }
      KEY_YEN-KEY_3: { launch: ["swaymsg", "workspace", "comm." ] }
      KEY_YEN-KEY_4: { launch: ["swaymsg", "move", "container", "to", "workspace", "main"  ] }
      KEY_YEN-KEY_5: { launch: ["swaymsg", "move", "container", "to", "workspace", "sub"   ] }
      KEY_YEN-KEY_6: { launch: ["swaymsg", "move", "container", "to", "workspace", "comm." ] }
      # layout
      KEY_YEN-KEY_COMMA: { launch: ["swaymsg", "layout", "tabbed"] }
      KEY_YEN-KEY_DOT:   { launch: ["swaymsg", "splith"] }
      KEY_YEN-KEY_SLASH: { launch: ["swaymsg", "layout", "toggle", "split"] }
      KEY_YEN-KEY_E:     { launch: ["swaymsg", "fullscreen"] }
      # Enter resize mode
      KEY_YEN-KEY_S: { set_mode: resize }
      # Space-layer: to here

      SUPER_R-KEY_Q: { launch: ["swaymsg", "kill"] }
      SUPER_R-KEY_SPACE: { launch: ["swaymsg", "exec", "rofi -show drun"] }

      ALT_L-SHIFT_L-KEY_C: { launch: ["swaymsg", "reload"] }

  - name: Sway commands (resize mode)
    mode: resize
    remap:
      KEY_ESC: { set_mode: default }
      KEY_H: { launch: ["swaymsg", "resize", "shrink", "width", "20px"] }
      KEY_L: { launch: ["swaymsg", "resize", "grow",   "width", "20px"] }
      KEY_LEFT:  { launch: ["swaymsg", "resize", "shrink", "width", "100px"] }
      KEY_RIGHT: { launch: ["swaymsg", "resize", "grow",   "width", "100px"] }

  - name: Alternative keybinding for Backspace
    remap:
      CTRL_L-KEY_LEFTBRACE: KEY_BACKSPACE

  - name: Left Ctrl + hjkl to arrow keys
    remap:
      CTRL_L-KEY_H: KEY_LEFT
      CTRL_L-KEY_J: KEY_DOWN
      CTRL_L-KEY_K: KEY_UP
      CTRL_L-KEY_L: KEY_RIGHT

  - name: Adapt the order of arrow keys to Vim style
    remap:
      KEY_UP: KEY_DOWN
      KEY_DOWN: KEY_UP

  - name: Brave Rule
    application:
      only: Brave-browser
    remap:
      CTRL_L-KEY_MINUS: ALT-KEY_LEFT  # Back
      CTRL_L-KEY_EQUAL: ALT-KEY_RIGHT # Forward

      SUPER_R-KEY_RIGHTBRACE: CTRL-KEY_PAGEDOWN # Next tab
      SUPER_R-KEY_LEFTBRACE:  CTRL-KEY_PAGEUP   # Previous tab

      SUPER_R-KEY_E: CTRL-KEY_F # Find

  - name: My original keyboard layout based on colemak
    remap:
      KEY_D: KEY_S
      KEY_E: KEY_F
      KEY_F: KEY_T
      KEY_G: KEY_D
      KEY_I: KEY_U
      KEY_J: KEY_N
      KEY_K: KEY_E
      KEY_L: KEY_I
      KEY_N: KEY_K
      KEY_O: KEY_G
      KEY_P: KEY_Y
      KEY_R: KEY_P
      KEY_S: KEY_R
      KEY_T: KEY_SEMICOLON
      KEY_U: KEY_L
      KEY_Y: KEY_J
      KEY_SEMICOLON: KEY_O

default_mode: default
