modmap:
  - name: Physical JIS keyboard with ANSI layout
    remap:
      KEY_RO: KEY_RIGHTCTRL

  - name: Alternative keybindings for Ctrl and Esc
    remap:
      KEY_CAPSLOCK:
        held: KEY_LEFTCTRL
        alone: KEY_ESC
        alone_timeout_millis: 400

  - name: use Space as the Hyper key
    remap:
      KEY_SPACE:
        held: [KEY_LEFTMETA, KEY_LEFTALT, KEY_LEFTCTRL, KEY_LEFTSHIFT]
        alone: KEY_SPACE
        alone_timeout_millis: 300

keymap:
  - name: Brave Rule
    application:
      only: Brave-browser
    remap:
      CTRL_L-KEY_MINUS: ALT-KEY_LEFT  # Back
      CTRL_L-KEY_EQUAL: ALT-KEY_RIGHT # Forward
      SUPER_R-KEY_RIGHTBRACE: CTRL-KEY_PAGEDOWN # Next tab
      SUPER_R-KEY_LEFTBRACE:  CTRL-KEY_PAGEUP   # Previous tab
      SUPER_R-KEY_E: CTRL-KEY_F # Find
      SUPER_R-KEY_W: CTRL-KEY_W # Close tab
      SUPER_R-KEY_F: CTRL-KEY_T # New tab
      SUPER_R-KEY_A: CTRL-KEY_A # Select all
      SUPER_R-KEY_S: CTRL-KEY_R # Reload
      SUPER_R-KEY_C: CTRL-KEY_C # Copy
      SUPER_L-KEY_MINUS: CTRL-KEY_MINUS # Zoom out
      SUPER_L-KEY_EQUAL: CTRL-KEY_EQUAL # Zoom in
      SUPER_L-KEY_U: CTRL-KEY_L # Focus location
      SUPER_L-KEY_J: CTRL-KEY_N # New window
      SUPER_L-SHIFT_L-KEY_J: CTRL-SHIFT-KEY_N # New private window

  - name: Obsidian Rule
    application:
      only: obsidian
    remap:
      SUPER_R-KEY_C: CTRL-KEY_C
      SUPER_R-KEY_V: CTRL-KEY_V
      SUPER_R-KEY_X: CTRL-KEY_X
      SUPER_R-KEY_Z: CTRL-KEY_Z
      SUPER_R-KEY_A: CTRL-KEY_A

  - name: Alternative keybinding for Backspace
    remap:
      CTRL_L-KEY_LEFTBRACE: KEY_BACKSPACE

  - name: Left Ctrl + hjkl to arrow keys
    remap:
      CTRL_L-KEY_H: KEY_LEFT
      CTRL_L-KEY_J: KEY_DOWN
      CTRL_L-KEY_K: KEY_UP
      CTRL_L-KEY_L: KEY_RIGHT

  - name: Adapt the order of arrow keys to Vim style
    remap:
      KEY_UP: KEY_DOWN
      KEY_DOWN: KEY_UP

  - name: My original keyboard layout based on colemak
    remap:
      KEY_D: KEY_S
      KEY_E: KEY_F
      KEY_F: KEY_T
      KEY_G: KEY_D
      KEY_I: KEY_U
      KEY_J: KEY_N
      KEY_K: KEY_E
      KEY_L: KEY_I
      KEY_N: KEY_K
      KEY_O: KEY_G
      KEY_P: KEY_Y
      KEY_R: KEY_P
      KEY_S: KEY_R
      KEY_T: KEY_SEMICOLON
      KEY_U: KEY_L
      KEY_Y: KEY_J
      KEY_SEMICOLON: KEY_O
